name: Script
version: 1.0
main: de.AhegaHOE.main.Main
author: AhegaHOE
commands:
  o:
    description: Allows the player to text global
  gamemode:
    aliases: [ gm ]
    description: Allows the player to change their gamemode
  heal:
    description: Allows the player to heal themselfs
  me:
    description: Allows the player to perform actions
  w:
    aliases: [ whisper ]
    description: Allows the player to whisper in roleplay
  buildmode:
    aliases: [ bm ]
    description: Allows the player to enter the build mode
  s:
    aliases: [ schreien, shout ]
    description: Allows the player to shout in roleplay
  time:
    description: Allows the player to check the reallife time
  adminduty:
    aliases: [ aduty, admindienst ]
    description: Allows the player to enter the adminduty
  afk:
    description: Allows the player to enter the afk-mode
  tp:
    aliases: [ teleport, teleportieren ]
    description: Allows the player to teleport themselfs
  id:
    description: Allows the player to see informations about certain players
  kuss:
    aliases: [ kiss ]
    description: Allows the player to kiss other players
  oos:
    aliases: [ ooc ]
    description: Allows the player to chat out of the roleplay situation
  suicide:
    description: Allows the player to commit suicide
  stats:
    aliases: [ money, statistics, geld ]
    description: Allows the player to see their stats
  checkfinances:
    description: Allows the player to see the financial status of other players
  showfinances:
    description: Allows the player to show other their finances
  moneymanagement:
    description: Allows the player to manage the money of other players
  pay:
    description: Allows the player to pay money to other players
  bank:
    description: Allows the player to access their bank account.
  checkplayer:
    description: Allows the player to check different parameters of other players.
  clearchat:
    description: Allows the player to clear the chat.
    aliases: [ cc ]
  vanish:
    description: Allows the player to hide themselfes.
    aliases: [ v ]
  commandspy:
    description: Allows the player to spy the commands that other players execute.
    aliases: [ notify, cmdspy ]
  inventorysee:
    description: Allows the player to see the inventory of other players.
    aliases: [ invsee ]
  kick:
    description: Allows the player to kick other players.
  dice:
    description: Allows the player to roll a dice.
  coinflip:
    description: Allows the player to throw a coin.
    aliases: [ headsortails, kopfoderzahl, koz, hot ]
  registeratm:
    description: Allows the player to register a atm.
  forum:
    description: Allows the player to open the forum.
  help:
    description: Allows the player to get help.
    aliases: [ report, ticket ]
  cancelreport:
    description: Allows the player to cancel the report queue.
  acceptreport:
    description: Allows the player to accept a report.
  closereport:
    description: Allows the player to close a report.
  togglereportchat:
    description: Allows the player to toggle the report chat.
    aliases: [ togglerc, trc ]
  calculate:
    description: Allows the player to calculate math expressions.
    aliases: [ calc, rechner, taschenrechner, calculator ]
  testcommand:
    description: Allows the player to test commands.
  ban:
    description: Allows the player to ban other players.
  unban:
    description: Allows the player to unban other players.
  checkbanid:
    description: Allows the player to check the infos of certain ban-ids.
  checkbans:
    description: Allows the player to check the ban-ids of a player.
  tempban:
    description: Allows the player to tempban other players.
    aliases: [ timeban ]
  ts:
    description: Allows the player to see infomation about the teamspeak server.
    aliases: [ teamspeak, teamspeak3, ts3 ]
  uuid:
    description: Allows the player to get their uuid.
    aliases: [ uniqueuserid, userid ]